name: CI

#Automate the process of the jobs ( on)#
on:
  push:
    branches: [ master ] #master = name of branch #
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest   #will run on latest version (linux) ubuntu virtual machine#

    steps:
    - name: Checkout code
      uses: actions/checkout@v4    #copy the code from branch to virtual machine#

    - name: Set up JDK 17           
      uses: actions/setup-java@v3   #install java #
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle
      run: gradle build               # run the jar file in the build.gradle#

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3  #copy the file from virtual machine to github (if u wan to keep the file)#
      with:
        name: build-artifacts
        path: build/libs/**       #upload all the files in the libs  (define in gradle)

    - name: Run Unit Test           
      run: gradle test                # run unit test (in the gradle.build)

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3        #upload the report 
      with:
        name: test-reports
        path: build/reports/tests/**          #all the files(in virtual machine) in this path will be uploaded to the github#
        
    - name: Generate code coverage report
      run: gradle jacocoTestReport            

    - name: Upload code coverage report
      uses: actions/upload-artifact@v3      #upload the report#
      with:
        name: code-coverage-report
        path: build/reports/jacoco/test/html/**
        
    - name: Run Deployment
      run: java -jar build/libs/hello-world-java-V1.jar         

